
// Generated by MyGeneration Version # (1.3.0.3)

using System;

namespace cfd.FacturaElectronica
{
	public class cfdLogFacturaXML : _cfdLogFacturaXML
	{
		public cfdLogFacturaXML(string connstr)
		{
            this.ConnectionString = connstr;
	
		}
	}
}
