//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Encriptador.interfactura {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultaTimbreOperationCompleted;
        
        private System.Threading.SendOrPostCallback GeneraTimbreOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelaTimbreOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::Encriptador.Properties.Settings.Default.Encriptador_interfactura_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultaTimbreCompletedEventHandler ConsultaTimbreCompleted;
        
        /// <remarks/>
        public event GeneraTimbreCompletedEventHandler GeneraTimbreCompleted;
        
        /// <remarks/>
        public event CancelaTimbreCompletedEventHandler CancelaTimbreCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaTimbre", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaTimbre(string UUID, System.DateTime FechaTimbrado, bool SoloTimbrado) {
            object[] results = this.Invoke("ConsultaTimbre", new object[] {
                        UUID,
                        FechaTimbrado,
                        SoloTimbrado});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaTimbreAsync(string UUID, System.DateTime FechaTimbrado, bool SoloTimbrado) {
            this.ConsultaTimbreAsync(UUID, FechaTimbrado, SoloTimbrado, null);
        }
        
        /// <remarks/>
        public void ConsultaTimbreAsync(string UUID, System.DateTime FechaTimbrado, bool SoloTimbrado, object userState) {
            if ((this.ConsultaTimbreOperationCompleted == null)) {
                this.ConsultaTimbreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaTimbreOperationCompleted);
            }
            this.InvokeAsync("ConsultaTimbre", new object[] {
                        UUID,
                        FechaTimbrado,
                        SoloTimbrado}, this.ConsultaTimbreOperationCompleted, userState);
        }
        
        private void OnConsultaTimbreOperationCompleted(object arg) {
            if ((this.ConsultaTimbreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaTimbreCompleted(this, new ConsultaTimbreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GeneraTimbre", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GeneraTimbre(string CFDv3, bool Solotimbre) {
            object[] results = this.Invoke("GeneraTimbre", new object[] {
                        CFDv3,
                        Solotimbre});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GeneraTimbreAsync(string CFDv3, bool Solotimbre) {
            this.GeneraTimbreAsync(CFDv3, Solotimbre, null);
        }
        
        /// <remarks/>
        public void GeneraTimbreAsync(string CFDv3, bool Solotimbre, object userState) {
            if ((this.GeneraTimbreOperationCompleted == null)) {
                this.GeneraTimbreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeneraTimbreOperationCompleted);
            }
            this.InvokeAsync("GeneraTimbre", new object[] {
                        CFDv3,
                        Solotimbre}, this.GeneraTimbreOperationCompleted, userState);
        }
        
        private void OnGeneraTimbreOperationCompleted(object arg) {
            if ((this.GeneraTimbreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GeneraTimbreCompleted(this, new GeneraTimbreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CancelaTimbre", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CancelaTimbre(string CancelaXML) {
            object[] results = this.Invoke("CancelaTimbre", new object[] {
                        CancelaXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CancelaTimbreAsync(string CancelaXML) {
            this.CancelaTimbreAsync(CancelaXML, null);
        }
        
        /// <remarks/>
        public void CancelaTimbreAsync(string CancelaXML, object userState) {
            if ((this.CancelaTimbreOperationCompleted == null)) {
                this.CancelaTimbreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelaTimbreOperationCompleted);
            }
            this.InvokeAsync("CancelaTimbre", new object[] {
                        CancelaXML}, this.CancelaTimbreOperationCompleted, userState);
        }
        
        private void OnCancelaTimbreOperationCompleted(object arg) {
            if ((this.CancelaTimbreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelaTimbreCompleted(this, new CancelaTimbreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ConsultaTimbreCompletedEventHandler(object sender, ConsultaTimbreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaTimbreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaTimbreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GeneraTimbreCompletedEventHandler(object sender, GeneraTimbreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GeneraTimbreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GeneraTimbreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void CancelaTimbreCompletedEventHandler(object sender, CancelaTimbreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelaTimbreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelaTimbreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591