//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfdiEntidadesGP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PER10Entities : DbContext
    {
        public PER10Entities()
            : base("name=PER10Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vwCfdiRelacionados> vwCfdiRelacionados { get; set; }
        public virtual DbSet<vwCfdiGeneraResumenDiario> vwCfdiGeneraResumenDiario { get; set; }
        public virtual DbSet<vwCfdiConceptos> vwCfdiConceptos { get; set; }
        public virtual DbSet<vwCfdiGeneraDocumentoDeVenta> vwCfdiGeneraDocumentoDeVenta { get; set; }
    
        [DbFunction("PER10Entities", "fCfdiParametrosTipoLeyenda")]
        public virtual IQueryable<fCfdiParametrosTipoLeyenda_Result> fCfdiParametrosTipoLeyenda(string aDRSCODE, string master_Type)
        {
            var aDRSCODEParameter = aDRSCODE != null ?
                new ObjectParameter("ADRSCODE", aDRSCODE) :
                new ObjectParameter("ADRSCODE", typeof(string));
    
            var master_TypeParameter = master_Type != null ?
                new ObjectParameter("Master_Type", master_Type) :
                new ObjectParameter("Master_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fCfdiParametrosTipoLeyenda_Result>("[PER10Entities].[fCfdiParametrosTipoLeyenda](@ADRSCODE, @Master_Type)", aDRSCODEParameter, master_TypeParameter);
        }
    }
}
