/*
'===============================================================================
'  Generated From - CSharp_dOOdads_View.vbgen
'
'  The supporting base class SqlClientEntity is in the 
'  Architecture directory in "dOOdads".
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace cfd.FacturaElectronica
{
	public class vwCfdIdDocumentos : SqlClientEntity
	{
		public vwCfdIdDocumentos()
		{
			this.QuerySource = "vwCfdIdDocumentos";
			this.MappingName = "vwCfdIdDocumentos";
		}	
	
		//4/11/10 jcf Crea constructor con cadena de conexión
		public vwCfdIdDocumentos(string connstr)
		{
			this.ConnectionString = connstr;
			this.QuerySource = "vwCfdIdDocumentos";
			this.MappingName = "vwCfdIdDocumentos";
		}	
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			return base.Query.Load();
		}
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
	
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter Soptype
			{
				get
				{
					return new SqlParameter("@Soptype", SqlDbType.SmallInt, 0);
				}
			}
			
			public static SqlParameter Docid
			{
				get
				{
					return new SqlParameter("@Docid", SqlDbType.Char, 15);
				}
			}
			
			public static SqlParameter SOPNUMBE
			{
				get
				{
					return new SqlParameter("@SOPNUMBE", SqlDbType.Char, 21);
				}
			}
			
		}
		#endregion	
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string Soptype = "soptype";
            public const string Docid = "docid";
            public const string SOPNUMBE = "SOPNUMBE";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Soptype] = vwCfdIdDocumentos.PropertyNames.Soptype;
					ht[Docid] = vwCfdIdDocumentos.PropertyNames.Docid;
					ht[SOPNUMBE] = vwCfdIdDocumentos.PropertyNames.SOPNUMBE;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string Soptype = "Soptype";
            public const string Docid = "Docid";
            public const string SOPNUMBE = "SOPNUMBE";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Soptype] = vwCfdIdDocumentos.ColumnNames.Soptype;
					ht[Docid] = vwCfdIdDocumentos.ColumnNames.Docid;
					ht[SOPNUMBE] = vwCfdIdDocumentos.ColumnNames.SOPNUMBE;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string Soptype = "s_Soptype";
            public const string Docid = "s_Docid";
            public const string SOPNUMBE = "s_SOPNUMBE";

		}
		#endregion	
		
		#region Properties
			public virtual short Soptype
	    {
			get
	        {
				return base.Getshort(ColumnNames.Soptype);
			}
			set
	        {
				base.Setshort(ColumnNames.Soptype, value);
			}
		}

		public virtual string Docid
	    {
			get
	        {
				return base.Getstring(ColumnNames.Docid);
			}
			set
	        {
				base.Setstring(ColumnNames.Docid, value);
			}
		}

		public virtual string SOPNUMBE
	    {
			get
	        {
				return base.Getstring(ColumnNames.SOPNUMBE);
			}
			set
	        {
				base.Setstring(ColumnNames.SOPNUMBE, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_Soptype
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Soptype) ? string.Empty : base.GetshortAsString(ColumnNames.Soptype);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Soptype);
				else
					this.Soptype = base.SetshortAsString(ColumnNames.Soptype, value);
			}
		}

		public virtual string s_Docid
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Docid) ? string.Empty : base.GetstringAsString(ColumnNames.Docid);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Docid);
				else
					this.Docid = base.SetstringAsString(ColumnNames.Docid, value);
			}
		}

		public virtual string s_SOPNUMBE
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.SOPNUMBE) ? string.Empty : base.GetstringAsString(ColumnNames.SOPNUMBE);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.SOPNUMBE);
				else
					this.SOPNUMBE = base.SetstringAsString(ColumnNames.SOPNUMBE, value);
			}
		}


		#endregion			
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter Soptype
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Soptype, Parameters.Soptype);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Docid
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Docid, Parameters.Docid);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter SOPNUMBE
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.SOPNUMBE, Parameters.SOPNUMBE);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter Soptype
		    {
				get
		        {
					if(_Soptype_W == null)
	        	    {
						_Soptype_W = TearOff.Soptype;
					}
					return _Soptype_W;
				}
			}

			public WhereParameter Docid
		    {
				get
		        {
					if(_Docid_W == null)
	        	    {
						_Docid_W = TearOff.Docid;
					}
					return _Docid_W;
				}
			}

			public WhereParameter SOPNUMBE
		    {
				get
		        {
					if(_SOPNUMBE_W == null)
	        	    {
						_SOPNUMBE_W = TearOff.SOPNUMBE;
					}
					return _SOPNUMBE_W;
				}
			}

			private WhereParameter _Soptype_W = null;
			private WhereParameter _Docid_W = null;
			private WhereParameter _SOPNUMBE_W = null;

			public void WhereClauseReset()
			{
				_Soptype_W = null;
				_Docid_W = null;
				_SOPNUMBE_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter Soptype
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Soptype, Parameters.Soptype);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Docid
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Docid, Parameters.Docid);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter SOPNUMBE
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.SOPNUMBE, Parameters.SOPNUMBE);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter Soptype
		    {
				get
		        {
					if(_Soptype_W == null)
	        	    {
						_Soptype_W = TearOff.Soptype;
					}
					return _Soptype_W;
				}
			}

			public AggregateParameter Docid
		    {
				get
		        {
					if(_Docid_W == null)
	        	    {
						_Docid_W = TearOff.Docid;
					}
					return _Docid_W;
				}
			}

			public AggregateParameter SOPNUMBE
		    {
				get
		        {
					if(_SOPNUMBE_W == null)
	        	    {
						_SOPNUMBE_W = TearOff.SOPNUMBE;
					}
					return _SOPNUMBE_W;
				}
			}

			private AggregateParameter _Soptype_W = null;
			private AggregateParameter _Docid_W = null;
			private AggregateParameter _SOPNUMBE_W = null;

			public void AggregateClauseReset()
			{
				_Soptype_W = null;
				_Docid_W = null;
				_SOPNUMBE_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
			return null;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
			return null;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
			return null;
		}
	}
}
