//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace cfdiPeruOperadorServiciosElectronicos.pe.dfacture.ws {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MetodosClientSoap", Namespace="http://Dfactur-e.com/")]
    public partial class MetodosClient : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ComunicacionBajaOperationCompleted;
        
        private System.Threading.SendOrPostCallback DescargaXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback DescargaPDFOperationCompleted;
        
        private System.Threading.SendOrPostCallback DescargaCDROperationCompleted;
        
        private System.Threading.SendOrPostCallback DownloadCDROperationCompleted;
        
        private System.Threading.SendOrPostCallback EstatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDocumentStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuiasRemisionOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperaPeticionOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetencionPercepcionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResumenDiarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReversionOperationCompleted;
        
        private System.Threading.SendOrPostCallback timbraEnviaTXT32OperationCompleted;
        
        private System.Threading.SendOrPostCallback TimbresRestantesOperationCompleted;
        
        private System.Threading.SendOrPostCallback validaAccesosOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetCertificadoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MetodosClient() {
            this.Url = global::cfdiPeruOperadorServiciosElectronicos.Properties.Settings.Default.cfdiPeruDFactureWS_pe_dfacture_ws_MetodosClient;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ComunicacionBajaCompletedEventHandler ComunicacionBajaCompleted;
        
        /// <remarks/>
        public event DescargaXMLCompletedEventHandler DescargaXMLCompleted;
        
        /// <remarks/>
        public event DescargaPDFCompletedEventHandler DescargaPDFCompleted;
        
        /// <remarks/>
        public event DescargaCDRCompletedEventHandler DescargaCDRCompleted;
        
        /// <remarks/>
        public event DownloadCDRCompletedEventHandler DownloadCDRCompleted;
        
        /// <remarks/>
        public event EstatusCompletedEventHandler EstatusCompleted;
        
        /// <remarks/>
        public event getDocumentStatusCompletedEventHandler getDocumentStatusCompleted;
        
        /// <remarks/>
        public event GuiasRemisionCompletedEventHandler GuiasRemisionCompleted;
        
        /// <remarks/>
        public event RecuperaPeticionCompletedEventHandler RecuperaPeticionCompleted;
        
        /// <remarks/>
        public event RetencionPercepcionCompletedEventHandler RetencionPercepcionCompleted;
        
        /// <remarks/>
        public event ResumenDiarioCompletedEventHandler ResumenDiarioCompleted;
        
        /// <remarks/>
        public event ReversionCompletedEventHandler ReversionCompleted;
        
        /// <remarks/>
        public event timbraEnviaTXT32CompletedEventHandler timbraEnviaTXT32Completed;
        
        /// <remarks/>
        public event TimbresRestantesCompletedEventHandler TimbresRestantesCompleted;
        
        /// <remarks/>
        public event validaAccesosCompletedEventHandler validaAccesosCompleted;
        
        /// <remarks/>
        public event SetCertificadoCompletedEventHandler SetCertificadoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Dfactur-e.com/ComunicacionBaja", RequestNamespace="http://Dfactur-e.com/", ResponseNamespace="http://Dfactur-e.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cancelacion ComunicacionBaja(string ruc, string user, string userPassword, string correlativo) {
            object[] results = this.Invoke("ComunicacionBaja", new object[] {
                        ruc,
                        user,
                        userPassword,
                        correlativo});
            return ((Cancelacion)(results[0]));
        }
        
        /// <remarks/>
        public void ComunicacionBajaAsync(string ruc, string user, string userPassword, string correlativo) {
            this.ComunicacionBajaAsync(ruc, user, userPassword, correlativo, null);
        }
        
        /// <remarks/>
        public void ComunicacionBajaAsync(string ruc, string user, string userPassword, string correlativo, object userState) {
            if ((this.ComunicacionBajaOperationCompleted == null)) {
                this.ComunicacionBajaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnComunicacionBajaOperationCompleted);
            }
            this.InvokeAsync("ComunicacionBaja", new object[] {
                        ruc,
                        user,
                        userPassword,
                        correlativo}, this.ComunicacionBajaOperationCompleted, userState);
        }
        
        private void OnComunicacionBajaOperationCompleted(object arg) {
            if ((this.ComunicacionBajaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ComunicacionBajaCompleted(this, new ComunicacionBajaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Dfactur-e.com/DescargaXML", RequestNamespace="http://Dfactur-e.com/", ResponseNamespace="http://Dfactur-e.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DescargaXML(string ruc, string documento) {
            object[] results = this.Invoke("DescargaXML", new object[] {
                        ruc,
                        documento});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DescargaXMLAsync(string ruc, string documento) {
            this.DescargaXMLAsync(ruc, documento, null);
        }
        
        /// <remarks/>
        public void DescargaXMLAsync(string ruc, string documento, object userState) {
            if ((this.DescargaXMLOperationCompleted == null)) {
                this.DescargaXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDescargaXMLOperationCompleted);
            }
            this.InvokeAsync("DescargaXML", new object[] {
                        ruc,
                        documento}, this.DescargaXMLOperationCompleted, userState);
        }
        
        private void OnDescargaXMLOperationCompleted(object arg) {
            if ((this.DescargaXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DescargaXMLCompleted(this, new DescargaXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Dfactur-e.com/DescargaPDF", RequestNamespace="http://Dfactur-e.com/", ResponseNamespace="http://Dfactur-e.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DescargaPDF(string ruc, string documento) {
            object[] results = this.Invoke("DescargaPDF", new object[] {
                        ruc,
                        documento});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DescargaPDFAsync(string ruc, string documento) {
            this.DescargaPDFAsync(ruc, documento, null);
        }
        
        /// <remarks/>
        public void DescargaPDFAsync(string ruc, string documento, object userState) {
            if ((this.DescargaPDFOperationCompleted == null)) {
                this.DescargaPDFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDescargaPDFOperationCompleted);
            }
            this.InvokeAsync("DescargaPDF", new object[] {
                        ruc,
                        documento}, this.DescargaPDFOperationCompleted, userState);
        }
        
        private void OnDescargaPDFOperationCompleted(object arg) {
            if ((this.DescargaPDFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DescargaPDFCompleted(this, new DescargaPDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Dfactur-e.com/DescargaCDR", RequestNamespace="http://Dfactur-e.com/", ResponseNamespace="http://Dfactur-e.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DescargaCDR(string ruc, string documento) {
            object[] results = this.Invoke("DescargaCDR", new object[] {
                        ruc,
                        documento});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DescargaCDRAsync(string ruc, string documento) {
            this.DescargaCDRAsync(ruc, documento, null);
        }
        
        /// <remarks/>
        public void DescargaCDRAsync(string ruc, string documento, object userState) {
            if ((this.DescargaCDROperationCompleted == null)) {
                this.DescargaCDROperationCompleted = new System.Threading.SendOrPostCallback(this.OnDescargaCDROperationCompleted);
            }
            this.InvokeAsync("DescargaCDR", new object[] {
                        ruc,
                        documento}, this.DescargaCDROperationCompleted, userState);
        }
        
        private void OnDescargaCDROperationCompleted(object arg) {
            if ((this.DescargaCDRCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DescargaCDRCompleted(this, new DescargaCDRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Dfactur-e.com/DownloadCDR", RequestNamespace="http://Dfactur-e.com/", ResponseNamespace="http://Dfactur-e.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DownloadResponse DownloadCDR(string user, string userPassword, string ruc, string documentName) {
            object[] results = this.Invoke("DownloadCDR", new object[] {
                        user,
                        userPassword,
                        ruc,
                        documentName});
            return ((DownloadResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DownloadCDRAsync(string user, string userPassword, string ruc, string documentName) {
            this.DownloadCDRAsync(user, userPassword, ruc, documentName, null);
        }
        
        /// <remarks/>
        public void DownloadCDRAsync(string user, string userPassword, string ruc, string documentName, object userState) {
            if ((this.DownloadCDROperationCompleted == null)) {
                this.DownloadCDROperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadCDROperationCompleted);
            }
            this.InvokeAsync("DownloadCDR", new object[] {
                        user,
                        userPassword,
                        ruc,
                        documentName}, this.DownloadCDROperationCompleted, userState);
        }
        
        private void OnDownloadCDROperationCompleted(object arg) {
            if ((this.DownloadCDRCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadCDRCompleted(this, new DownloadCDRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Dfactur-e.com/Estatus", RequestNamespace="http://Dfactur-e.com/", ResponseNamespace="http://Dfactur-e.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Proceso Estatus(string ruc, string user, string userPassword, string Nroticketdeatencion) {
            object[] results = this.Invoke("Estatus", new object[] {
                        ruc,
                        user,
                        userPassword,
                        Nroticketdeatencion});
            return ((Proceso)(results[0]));
        }
        
        /// <remarks/>
        public void EstatusAsync(string ruc, string user, string userPassword, string Nroticketdeatencion) {
            this.EstatusAsync(ruc, user, userPassword, Nroticketdeatencion, null);
        }
        
        /// <remarks/>
        public void EstatusAsync(string ruc, string user, string userPassword, string Nroticketdeatencion, object userState) {
            if ((this.EstatusOperationCompleted == null)) {
                this.EstatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEstatusOperationCompleted);
            }
            this.InvokeAsync("Estatus", new object[] {
                        ruc,
                        user,
                        userPassword,
                        Nroticketdeatencion}, this.EstatusOperationCompleted, userState);
        }
        
        private void OnEstatusOperationCompleted(object arg) {
            if ((this.EstatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EstatusCompleted(this, new EstatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Dfactur-e.com/getDocumentStatus", RequestNamespace="http://Dfactur-e.com/", ResponseNamespace="http://Dfactur-e.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StatusResponse getDocumentStatus(string ruc, string document) {
            object[] results = this.Invoke("getDocumentStatus", new object[] {
                        ruc,
                        document});
            return ((StatusResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getDocumentStatusAsync(string ruc, string document) {
            this.getDocumentStatusAsync(ruc, document, null);
        }
        
        /// <remarks/>
        public void getDocumentStatusAsync(string ruc, string document, object userState) {
            if ((this.getDocumentStatusOperationCompleted == null)) {
                this.getDocumentStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDocumentStatusOperationCompleted);
            }
            this.InvokeAsync("getDocumentStatus", new object[] {
                        ruc,
                        document}, this.getDocumentStatusOperationCompleted, userState);
        }
        
        private void OngetDocumentStatusOperationCompleted(object arg) {
            if ((this.getDocumentStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDocumentStatusCompleted(this, new getDocumentStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Dfactur-e.com/GuiasRemision", RequestNamespace="http://Dfactur-e.com/", ResponseNamespace="http://Dfactur-e.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StampingResult GuiasRemision(string ruc, string user, string userPassword, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] fileContent) {
            object[] results = this.Invoke("GuiasRemision", new object[] {
                        ruc,
                        user,
                        userPassword,
                        fileContent});
            return ((StampingResult)(results[0]));
        }
        
        /// <remarks/>
        public void GuiasRemisionAsync(string ruc, string user, string userPassword, byte[] fileContent) {
            this.GuiasRemisionAsync(ruc, user, userPassword, fileContent, null);
        }
        
        /// <remarks/>
        public void GuiasRemisionAsync(string ruc, string user, string userPassword, byte[] fileContent, object userState) {
            if ((this.GuiasRemisionOperationCompleted == null)) {
                this.GuiasRemisionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuiasRemisionOperationCompleted);
            }
            this.InvokeAsync("GuiasRemision", new object[] {
                        ruc,
                        user,
                        userPassword,
                        fileContent}, this.GuiasRemisionOperationCompleted, userState);
        }
        
        private void OnGuiasRemisionOperationCompleted(object arg) {
            if ((this.GuiasRemisionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuiasRemisionCompleted(this, new GuiasRemisionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Dfactur-e.com/RecuperaPeticion", RequestNamespace="http://Dfactur-e.com/", ResponseNamespace="http://Dfactur-e.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RespuestaTimbradoTXT RecuperaPeticion(string ruc, string documento) {
            object[] results = this.Invoke("RecuperaPeticion", new object[] {
                        ruc,
                        documento});
            return ((RespuestaTimbradoTXT)(results[0]));
        }
        
        /// <remarks/>
        public void RecuperaPeticionAsync(string ruc, string documento) {
            this.RecuperaPeticionAsync(ruc, documento, null);
        }
        
        /// <remarks/>
        public void RecuperaPeticionAsync(string ruc, string documento, object userState) {
            if ((this.RecuperaPeticionOperationCompleted == null)) {
                this.RecuperaPeticionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperaPeticionOperationCompleted);
            }
            this.InvokeAsync("RecuperaPeticion", new object[] {
                        ruc,
                        documento}, this.RecuperaPeticionOperationCompleted, userState);
        }
        
        private void OnRecuperaPeticionOperationCompleted(object arg) {
            if ((this.RecuperaPeticionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperaPeticionCompleted(this, new RecuperaPeticionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Dfactur-e.com/RetencionPercepcion", RequestNamespace="http://Dfactur-e.com/", ResponseNamespace="http://Dfactur-e.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StampingResult RetencionPercepcion(string ruc, string user, string userPassword, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] ContenidoArchivoTexto) {
            object[] results = this.Invoke("RetencionPercepcion", new object[] {
                        ruc,
                        user,
                        userPassword,
                        ContenidoArchivoTexto});
            return ((StampingResult)(results[0]));
        }
        
        /// <remarks/>
        public void RetencionPercepcionAsync(string ruc, string user, string userPassword, byte[] ContenidoArchivoTexto) {
            this.RetencionPercepcionAsync(ruc, user, userPassword, ContenidoArchivoTexto, null);
        }
        
        /// <remarks/>
        public void RetencionPercepcionAsync(string ruc, string user, string userPassword, byte[] ContenidoArchivoTexto, object userState) {
            if ((this.RetencionPercepcionOperationCompleted == null)) {
                this.RetencionPercepcionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetencionPercepcionOperationCompleted);
            }
            this.InvokeAsync("RetencionPercepcion", new object[] {
                        ruc,
                        user,
                        userPassword,
                        ContenidoArchivoTexto}, this.RetencionPercepcionOperationCompleted, userState);
        }
        
        private void OnRetencionPercepcionOperationCompleted(object arg) {
            if ((this.RetencionPercepcionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetencionPercepcionCompleted(this, new RetencionPercepcionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Dfactur-e.com/ResumenDiario", RequestNamespace="http://Dfactur-e.com/", ResponseNamespace="http://Dfactur-e.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Resumen ResumenDiario(string ruc, string user, string userPassword, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] ContenidoArchivoTexto) {
            object[] results = this.Invoke("ResumenDiario", new object[] {
                        ruc,
                        user,
                        userPassword,
                        ContenidoArchivoTexto});
            return ((Resumen)(results[0]));
        }
        
        /// <remarks/>
        public void ResumenDiarioAsync(string ruc, string user, string userPassword, byte[] ContenidoArchivoTexto) {
            this.ResumenDiarioAsync(ruc, user, userPassword, ContenidoArchivoTexto, null);
        }
        
        /// <remarks/>
        public void ResumenDiarioAsync(string ruc, string user, string userPassword, byte[] ContenidoArchivoTexto, object userState) {
            if ((this.ResumenDiarioOperationCompleted == null)) {
                this.ResumenDiarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResumenDiarioOperationCompleted);
            }
            this.InvokeAsync("ResumenDiario", new object[] {
                        ruc,
                        user,
                        userPassword,
                        ContenidoArchivoTexto}, this.ResumenDiarioOperationCompleted, userState);
        }
        
        private void OnResumenDiarioOperationCompleted(object arg) {
            if ((this.ResumenDiarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResumenDiarioCompleted(this, new ResumenDiarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Dfactur-e.com/Reversion", RequestNamespace="http://Dfactur-e.com/", ResponseNamespace="http://Dfactur-e.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cancelacion Reversion(string ruc, string user, string userPassword, string correlativo) {
            object[] results = this.Invoke("Reversion", new object[] {
                        ruc,
                        user,
                        userPassword,
                        correlativo});
            return ((Cancelacion)(results[0]));
        }
        
        /// <remarks/>
        public void ReversionAsync(string ruc, string user, string userPassword, string correlativo) {
            this.ReversionAsync(ruc, user, userPassword, correlativo, null);
        }
        
        /// <remarks/>
        public void ReversionAsync(string ruc, string user, string userPassword, string correlativo, object userState) {
            if ((this.ReversionOperationCompleted == null)) {
                this.ReversionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReversionOperationCompleted);
            }
            this.InvokeAsync("Reversion", new object[] {
                        ruc,
                        user,
                        userPassword,
                        correlativo}, this.ReversionOperationCompleted, userState);
        }
        
        private void OnReversionOperationCompleted(object arg) {
            if ((this.ReversionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReversionCompleted(this, new ReversionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Dfactur-e.com/timbraEnviaTXT32", RequestNamespace="http://Dfactur-e.com/", ResponseNamespace="http://Dfactur-e.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RespuestaTimbradoTXT timbraEnviaTXT32(string ruc, string user, string userPassword, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] ContenidoArchivoTexto) {
            object[] results = this.Invoke("timbraEnviaTXT32", new object[] {
                        ruc,
                        user,
                        userPassword,
                        ContenidoArchivoTexto});
            return ((RespuestaTimbradoTXT)(results[0]));
        }
        
        /// <remarks/>
        public void timbraEnviaTXT32Async(string ruc, string user, string userPassword, byte[] ContenidoArchivoTexto) {
            this.timbraEnviaTXT32Async(ruc, user, userPassword, ContenidoArchivoTexto, null);
        }
        
        /// <remarks/>
        public void timbraEnviaTXT32Async(string ruc, string user, string userPassword, byte[] ContenidoArchivoTexto, object userState) {
            if ((this.timbraEnviaTXT32OperationCompleted == null)) {
                this.timbraEnviaTXT32OperationCompleted = new System.Threading.SendOrPostCallback(this.OntimbraEnviaTXT32OperationCompleted);
            }
            this.InvokeAsync("timbraEnviaTXT32", new object[] {
                        ruc,
                        user,
                        userPassword,
                        ContenidoArchivoTexto}, this.timbraEnviaTXT32OperationCompleted, userState);
        }
        
        private void OntimbraEnviaTXT32OperationCompleted(object arg) {
            if ((this.timbraEnviaTXT32Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.timbraEnviaTXT32Completed(this, new timbraEnviaTXT32CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Dfactur-e.com/TimbresRestantes", RequestNamespace="http://Dfactur-e.com/", ResponseNamespace="http://Dfactur-e.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Timbresrestantes TimbresRestantes(string ruc, string user, string userPassword) {
            object[] results = this.Invoke("TimbresRestantes", new object[] {
                        ruc,
                        user,
                        userPassword});
            return ((Timbresrestantes)(results[0]));
        }
        
        /// <remarks/>
        public void TimbresRestantesAsync(string ruc, string user, string userPassword) {
            this.TimbresRestantesAsync(ruc, user, userPassword, null);
        }
        
        /// <remarks/>
        public void TimbresRestantesAsync(string ruc, string user, string userPassword, object userState) {
            if ((this.TimbresRestantesOperationCompleted == null)) {
                this.TimbresRestantesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimbresRestantesOperationCompleted);
            }
            this.InvokeAsync("TimbresRestantes", new object[] {
                        ruc,
                        user,
                        userPassword}, this.TimbresRestantesOperationCompleted, userState);
        }
        
        private void OnTimbresRestantesOperationCompleted(object arg) {
            if ((this.TimbresRestantesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TimbresRestantesCompleted(this, new TimbresRestantesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Dfactur-e.com/validaAccesos", RequestNamespace="http://Dfactur-e.com/", ResponseNamespace="http://Dfactur-e.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool validaAccesos(string ruc, string usuario, string password) {
            object[] results = this.Invoke("validaAccesos", new object[] {
                        ruc,
                        usuario,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void validaAccesosAsync(string ruc, string usuario, string password) {
            this.validaAccesosAsync(ruc, usuario, password, null);
        }
        
        /// <remarks/>
        public void validaAccesosAsync(string ruc, string usuario, string password, object userState) {
            if ((this.validaAccesosOperationCompleted == null)) {
                this.validaAccesosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidaAccesosOperationCompleted);
            }
            this.InvokeAsync("validaAccesos", new object[] {
                        ruc,
                        usuario,
                        password}, this.validaAccesosOperationCompleted, userState);
        }
        
        private void OnvalidaAccesosOperationCompleted(object arg) {
            if ((this.validaAccesosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validaAccesosCompleted(this, new validaAccesosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Dfactur-e.com/SetCertificado", RequestNamespace="http://Dfactur-e.com/", ResponseNamespace="http://Dfactur-e.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public certificateresponse SetCertificado(string user, string userPassword, string RUCEmisor, string certificado, string llave) {
            object[] results = this.Invoke("SetCertificado", new object[] {
                        user,
                        userPassword,
                        RUCEmisor,
                        certificado,
                        llave});
            return ((certificateresponse)(results[0]));
        }
        
        /// <remarks/>
        public void SetCertificadoAsync(string user, string userPassword, string RUCEmisor, string certificado, string llave) {
            this.SetCertificadoAsync(user, userPassword, RUCEmisor, certificado, llave, null);
        }
        
        /// <remarks/>
        public void SetCertificadoAsync(string user, string userPassword, string RUCEmisor, string certificado, string llave, object userState) {
            if ((this.SetCertificadoOperationCompleted == null)) {
                this.SetCertificadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetCertificadoOperationCompleted);
            }
            this.InvokeAsync("SetCertificado", new object[] {
                        user,
                        userPassword,
                        RUCEmisor,
                        certificado,
                        llave}, this.SetCertificadoOperationCompleted, userState);
        }
        
        private void OnSetCertificadoOperationCompleted(object arg) {
            if ((this.SetCertificadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetCertificadoCompleted(this, new SetCertificadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Dfactur-e.com/")]
    public partial class Cancelacion {
        
        private bool procesadoField;
        
        private string numeroErrorField;
        
        private string mensajeErrorField;
        
        private string xmlBajaField;
        
        private string nroticketdeatencionField;
        
        private string uUIDField;
        
        /// <remarks/>
        public bool Procesado {
            get {
                return this.procesadoField;
            }
            set {
                this.procesadoField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroError {
            get {
                return this.numeroErrorField;
            }
            set {
                this.numeroErrorField = value;
            }
        }
        
        /// <remarks/>
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
            }
        }
        
        /// <remarks/>
        public string XmlBaja {
            get {
                return this.xmlBajaField;
            }
            set {
                this.xmlBajaField = value;
            }
        }
        
        /// <remarks/>
        public string Nroticketdeatencion {
            get {
                return this.nroticketdeatencionField;
            }
            set {
                this.nroticketdeatencionField = value;
            }
        }
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Dfactur-e.com/")]
    public partial class certificateresponse {
        
        private bool procesadoField;
        
        private string numeroErrorField;
        
        private string mensajeErrorField;
        
        /// <remarks/>
        public bool Procesado {
            get {
                return this.procesadoField;
            }
            set {
                this.procesadoField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroError {
            get {
                return this.numeroErrorField;
            }
            set {
                this.numeroErrorField = value;
            }
        }
        
        /// <remarks/>
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Dfactur-e.com/")]
    public partial class Timbresrestantes {
        
        private bool procesadoField;
        
        private string numeroErrorField;
        
        private string mensajeErrorField;
        
        private string nrodeTicketsField;
        
        /// <remarks/>
        public bool Procesado {
            get {
                return this.procesadoField;
            }
            set {
                this.procesadoField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroError {
            get {
                return this.numeroErrorField;
            }
            set {
                this.numeroErrorField = value;
            }
        }
        
        /// <remarks/>
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
            }
        }
        
        /// <remarks/>
        public string NrodeTickets {
            get {
                return this.nrodeTicketsField;
            }
            set {
                this.nrodeTicketsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Dfactur-e.com/")]
    public partial class Resumen {
        
        private bool procesadoField;
        
        private string numeroErrorField;
        
        private string mensajeErrorField;
        
        private string xmlResumenField;
        
        private string nroticketdeatencionField;
        
        private string uUIDField;
        
        /// <remarks/>
        public bool Procesado {
            get {
                return this.procesadoField;
            }
            set {
                this.procesadoField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroError {
            get {
                return this.numeroErrorField;
            }
            set {
                this.numeroErrorField = value;
            }
        }
        
        /// <remarks/>
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
            }
        }
        
        /// <remarks/>
        public string XmlResumen {
            get {
                return this.xmlResumenField;
            }
            set {
                this.xmlResumenField = value;
            }
        }
        
        /// <remarks/>
        public string Nroticketdeatencion {
            get {
                return this.nroticketdeatencionField;
            }
            set {
                this.nroticketdeatencionField = value;
            }
        }
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Dfactur-e.com/")]
    public partial class RespuestaTimbradoTXT {
        
        private bool procesadoField;
        
        private string numeroErrorField;
        
        private string mensajeErrorField;
        
        private string xMLTimbradoField;
        
        private string uUIDField;
        
        private string idTransaccionField;
        
        private string sessionField;
        
        /// <remarks/>
        public bool Procesado {
            get {
                return this.procesadoField;
            }
            set {
                this.procesadoField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroError {
            get {
                return this.numeroErrorField;
            }
            set {
                this.numeroErrorField = value;
            }
        }
        
        /// <remarks/>
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
            }
        }
        
        /// <remarks/>
        public string XMLTimbrado {
            get {
                return this.xMLTimbradoField;
            }
            set {
                this.xMLTimbradoField = value;
            }
        }
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        public string IdTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
            }
        }
        
        /// <remarks/>
        public string session {
            get {
                return this.sessionField;
            }
            set {
                this.sessionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Dfactur-e.com/")]
    public partial class StampingResult {
        
        private bool processField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private string stampingXMLField;
        
        private string numerationField;
        
        private string transacctionIdField;
        
        private string sessionField;
        
        /// <remarks/>
        public bool Process {
            get {
                return this.processField;
            }
            set {
                this.processField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string StampingXML {
            get {
                return this.stampingXMLField;
            }
            set {
                this.stampingXMLField = value;
            }
        }
        
        /// <remarks/>
        public string Numeration {
            get {
                return this.numerationField;
            }
            set {
                this.numerationField = value;
            }
        }
        
        /// <remarks/>
        public string TransacctionId {
            get {
                return this.transacctionIdField;
            }
            set {
                this.transacctionIdField = value;
            }
        }
        
        /// <remarks/>
        public string Session {
            get {
                return this.sessionField;
            }
            set {
                this.sessionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Dfactur-e.com/")]
    public partial class StatusResponse {
        
        private string errorCodeField;
        
        private string statusField;
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Dfactur-e.com/")]
    public partial class Proceso {
        
        private bool procesadoField;
        
        private string numeroErrorField;
        
        private string mensajeErrorField;
        
        private string nroticketdeatencionField;
        
        /// <remarks/>
        public bool Procesado {
            get {
                return this.procesadoField;
            }
            set {
                this.procesadoField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroError {
            get {
                return this.numeroErrorField;
            }
            set {
                this.numeroErrorField = value;
            }
        }
        
        /// <remarks/>
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
            }
        }
        
        /// <remarks/>
        public string Nroticketdeatencion {
            get {
                return this.nroticketdeatencionField;
            }
            set {
                this.nroticketdeatencionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Dfactur-e.com/")]
    public partial class DownloadResponse {
        
        private string documentField;
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private bool processField;
        
        private string numerationField;
        
        private string transactionIdField;
        
        /// <remarks/>
        public string Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public bool Process {
            get {
                return this.processField;
            }
            set {
                this.processField = value;
            }
        }
        
        /// <remarks/>
        public string Numeration {
            get {
                return this.numerationField;
            }
            set {
                this.numerationField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ComunicacionBajaCompletedEventHandler(object sender, ComunicacionBajaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComunicacionBajaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ComunicacionBajaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cancelacion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cancelacion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DescargaXMLCompletedEventHandler(object sender, DescargaXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DescargaXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DescargaXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DescargaPDFCompletedEventHandler(object sender, DescargaPDFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DescargaPDFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DescargaPDFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DescargaCDRCompletedEventHandler(object sender, DescargaCDRCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DescargaCDRCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DescargaCDRCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DownloadCDRCompletedEventHandler(object sender, DownloadCDRCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadCDRCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadCDRCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DownloadResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DownloadResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void EstatusCompletedEventHandler(object sender, EstatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EstatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EstatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Proceso Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Proceso)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getDocumentStatusCompletedEventHandler(object sender, getDocumentStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDocumentStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDocumentStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StatusResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StatusResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GuiasRemisionCompletedEventHandler(object sender, GuiasRemisionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuiasRemisionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuiasRemisionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StampingResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StampingResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void RecuperaPeticionCompletedEventHandler(object sender, RecuperaPeticionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperaPeticionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperaPeticionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaTimbradoTXT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaTimbradoTXT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void RetencionPercepcionCompletedEventHandler(object sender, RetencionPercepcionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetencionPercepcionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetencionPercepcionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StampingResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StampingResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ResumenDiarioCompletedEventHandler(object sender, ResumenDiarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResumenDiarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ResumenDiarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Resumen Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Resumen)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ReversionCompletedEventHandler(object sender, ReversionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReversionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReversionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cancelacion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cancelacion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void timbraEnviaTXT32CompletedEventHandler(object sender, timbraEnviaTXT32CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class timbraEnviaTXT32CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal timbraEnviaTXT32CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaTimbradoTXT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaTimbradoTXT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void TimbresRestantesCompletedEventHandler(object sender, TimbresRestantesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TimbresRestantesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TimbresRestantesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Timbresrestantes Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Timbresrestantes)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void validaAccesosCompletedEventHandler(object sender, validaAccesosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validaAccesosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validaAccesosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SetCertificadoCompletedEventHandler(object sender, SetCertificadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetCertificadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetCertificadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public certificateresponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((certificateresponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591